sudo: required
services:
- docker
addons:
  apt:
    packages:
    - realpath
install:
- docker pull ubuntu:bionic
- wget https://raw.githubusercontent.com/Nitrux/nitrux-repository-util/master/nxos-repository-util.sh
  -O nxos-repository-util.sh
- chmod +x nxos-repository-util.sh
script:
- docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:bionic /bin/bash travis-build.sh
branches:
  only:
  - master
  - development
deploy:
- provider: script
  script: "./source/nxos-repository-util.sh upload testing *.deb"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: "./source/nxos-repository-util.sh upload development *.deb"
  skip_cleanup: true
  on:
    branch: development
notifications:
  email: false
  slack:
    secure: Vq2R/J4VAEIazB/m/B3+nMu/YDXExXJo+r2g08GcR+J6p7uMHndMZR2bi+zVgXpnBhGFVIcRNDJCrUqbeNAZl8ys1wiyf6sEDIwta/b/dOreeBsZF4G5BNhsb++TpRJQVqtgZNfsGo40tA5UU+VvE7DyhLaN8pPvtAy37VtZYltusF1GhcP3DimCzIlpwIzE7RUbiU07pHWmpaH/E/TMhb3Xegw6l6J3fiYoKJxeP1kMZ2YHzqf7Z14gh0uPq8mz8xvKqZq+i1g+/6egaSIXgC/iIfvHEppA6/H1fCP1CgzeJ+0FbQFP98PYtU4iznRGMpSdJK+hjsoMJqd+1hFHrT62OuCFiPQ1wNAbh0MXBzM8hObrDsW85E2uqvcZ5Ul2AyGxPgos4mnDX8pIC3bc0JlmESOgm2kMTJBuNUC7ujhBB4v6QFmM+xYPEi0tpXDPF+YkUg3Mna4229OI/IbPuFOpWwqC+BnJYIWaR/SOrBfUL+9Dzgi7utYhO8t9jxH5Tlqm7oTQhSwRUtimCfr/AS/oNLl3ppRTtVMYvXhbK3axxQ5eT5lqYpxUyB4x6bD+PzVOV9F95qu4jwt3AXcv78QUJsU1YZCqMmAEQ9uCJhFslSW8H6GcPXQUTT7vYEaBJX6tKkaaUD2mNotMlAf35dPrf2X+mqbOf04Ex2IFkzY=
env:
  global:
  - secure: obSfnDKZixUcjvTMyGI4iP2p4puR9dAt07rIo8X9srhz14upaA6J9GxJGBIKhj6qg5dAZPJExhLoNWwchWb04ON/Ny91JA5dOhhh5atmgVaxaHeVifJWRO4HRKJRvfMRRa4biHYP1WGcBsmDW9e32ivU3sdDsFRzzFJkmsN1r7u4aOw1XoD5bVD/RsKMtCh9PMp9zFSPwO8umHRASDpVrifz1YNfOwltoc7TTh6bk5jxoVAfIK4sfwFfIWxbs9s95YcuKafwwgTVDfkTKK15ageXgm9QUpZkuTgmoSud0Y0A6dfk38SUUITPpxeLyhiD/WNageMtNwcEdomMRuhilMDwCklKc6Wc/DoRwSUhB+jEumCBamQaEhHMRAZI7vhI8c90BVSCdXmBw7uE2yYtVuYLJCrQ1lryfmQ6lzW3oS4Q0A0xyXyYtebO0jymdc4Sr3mEoySNaRzYfyQhrM8rKhmr8N4sBeMSE5x+pNilyqwLTWrfbJ4wBoKmWNf/wmHr0u2vVBNvaJ/96bXWwOqK3hmwhlozhegsEdqXxJ/tFC0cq5LAbOuFtZRF4ne0j/CC3Qu3Z3BHrtMBy3ELPlJ6SNWDh7fVC5+ezy90awpfg4fMzyBP+QOssAZVlBD8cwHk/fLVlELAZq3YsgEAzX2gSQGQhzULVnF9OHSbQrGn01w=
  - secure: endAzGP11w52gHylR6D9qBmXfoSZQK+V3FDm0LTbkQ03hzdnGyuIl0ocMs1JNk5ClXpwdVN0sYfdHQAIGBMOQFo7OlNr8vTcO9Bz/j0h7nwzakiuLtRRIcXAXyd3spPwSISIs1YLsi5KRK7Ht+l6A7Q0DsrElpQFOXA2UXXbbfSjIi41lckXihGQ9dDDFK4PhYmVyeS0/09gHa5qkzNBnunydJWyWcRVbwegmJ1S52MdAcKJj80O9C1PmIOKTslIjF57LYP6mtD4KOGBGeH2qWou0Un9oWeNUF1//4R/RvxveeXd/vkT2xIvWFlktQMPdVtxTa0tchuVQtr7dkJtZvQPPb6kA+OKvRdA/t7RgZj0GfdT9+vU2ivkEoDCwTK09fN+emtdktAGaXM8KOImnN6uFlRkhB20Id1tYkI5JrW9oDOCX7Ite0m3iFN7H7BBTiqQJKW0OimXRqRTvcoq7WltmqdeDL5hKid2CSdT/1+wcOm7vF6/c6fqIAQpI6aEh56F3gQkok3W4z3iH472lDLrHjXXECihUoEauAAQ+Io/kBOsp8zN+avfjAx5N86iXbml+Jt1PGUKrdXzRpGTXe51k+DXt/eqvuz1/Bwg3V8IUDau9gMAl3vCfrMSlRYKy5YDi+6gAFhXIW3yWUMp21f3sEUS/U+1LH+ke4wWlXk=
